package com.xxg.jcatch.mbg.mapper;

import com.xxg.jcatch.mbg.bean.TException;
import com.xxg.jcatch.mbg.bean.TExceptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TExceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    long countByExample(TExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    int deleteByExample(TExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    int insert(TException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    int insertSelective(TException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    List<TException> selectByExample(TExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    TException selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TException record, @Param("example") TExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TException record, @Param("example") TExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TException record);
}