package com.xxg.jcatch.mbg.bean;

import java.io.Serializable;

public class TApp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.secret_key
     *
     * @mbg.generated
     */
    private String secretKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.subscriber
     *
     * @mbg.generated
     */
    private String subscriber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.id
     *
     * @return the value of t_app.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.id
     *
     * @param id the value for t_app.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.name
     *
     * @return the value of t_app.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.name
     *
     * @param name the value for t_app.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.description
     *
     * @return the value of t_app.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.description
     *
     * @param description the value for t_app.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.secret_key
     *
     * @return the value of t_app.secret_key
     *
     * @mbg.generated
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.secret_key
     *
     * @param secretKey the value for t_app.secret_key
     *
     * @mbg.generated
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.subscriber
     *
     * @return the value of t_app.subscriber
     *
     * @mbg.generated
     */
    public String getSubscriber() {
        return subscriber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.subscriber
     *
     * @param subscriber the value for t_app.subscriber
     *
     * @mbg.generated
     */
    public void setSubscriber(String subscriber) {
        this.subscriber = subscriber;
    }
}