package com.xxg.jcatch.mbg.bean;

import java.io.Serializable;
import java.util.Date;

public class TException implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.remote_addr
     *
     * @mbg.generated
     */
    private String remoteAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.exception_name
     *
     * @mbg.generated
     */
    private String exceptionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.stack_trace
     *
     * @mbg.generated
     */
    private String stackTrace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.method_name
     *
     * @mbg.generated
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.line_number
     *
     * @mbg.generated
     */
    private Integer lineNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.occurrence_number
     *
     * @mbg.generated
     */
    private Integer occurrenceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.last_submit_time
     *
     * @mbg.generated
     */
    private Date lastSubmitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exception
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.id
     *
     * @return the value of t_exception.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.id
     *
     * @param id the value for t_exception.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.app_id
     *
     * @return the value of t_exception.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.app_id
     *
     * @param appId the value for t_exception.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.remote_addr
     *
     * @return the value of t_exception.remote_addr
     *
     * @mbg.generated
     */
    public String getRemoteAddr() {
        return remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.remote_addr
     *
     * @param remoteAddr the value for t_exception.remote_addr
     *
     * @mbg.generated
     */
    public void setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.exception_name
     *
     * @return the value of t_exception.exception_name
     *
     * @mbg.generated
     */
    public String getExceptionName() {
        return exceptionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.exception_name
     *
     * @param exceptionName the value for t_exception.exception_name
     *
     * @mbg.generated
     */
    public void setExceptionName(String exceptionName) {
        this.exceptionName = exceptionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.message
     *
     * @return the value of t_exception.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.message
     *
     * @param message the value for t_exception.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.stack_trace
     *
     * @return the value of t_exception.stack_trace
     *
     * @mbg.generated
     */
    public String getStackTrace() {
        return stackTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.stack_trace
     *
     * @param stackTrace the value for t_exception.stack_trace
     *
     * @mbg.generated
     */
    public void setStackTrace(String stackTrace) {
        this.stackTrace = stackTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.class_name
     *
     * @return the value of t_exception.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.class_name
     *
     * @param className the value for t_exception.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.method_name
     *
     * @return the value of t_exception.method_name
     *
     * @mbg.generated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.method_name
     *
     * @param methodName the value for t_exception.method_name
     *
     * @mbg.generated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.file_name
     *
     * @return the value of t_exception.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.file_name
     *
     * @param fileName the value for t_exception.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.line_number
     *
     * @return the value of t_exception.line_number
     *
     * @mbg.generated
     */
    public Integer getLineNumber() {
        return lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.line_number
     *
     * @param lineNumber the value for t_exception.line_number
     *
     * @mbg.generated
     */
    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.occurrence_number
     *
     * @return the value of t_exception.occurrence_number
     *
     * @mbg.generated
     */
    public Integer getOccurrenceNumber() {
        return occurrenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.occurrence_number
     *
     * @param occurrenceNumber the value for t_exception.occurrence_number
     *
     * @mbg.generated
     */
    public void setOccurrenceNumber(Integer occurrenceNumber) {
        this.occurrenceNumber = occurrenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.create_time
     *
     * @return the value of t_exception.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.create_time
     *
     * @param createTime the value for t_exception.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.last_submit_time
     *
     * @return the value of t_exception.last_submit_time
     *
     * @mbg.generated
     */
    public Date getLastSubmitTime() {
        return lastSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.last_submit_time
     *
     * @param lastSubmitTime the value for t_exception.last_submit_time
     *
     * @mbg.generated
     */
    public void setLastSubmitTime(Date lastSubmitTime) {
        this.lastSubmitTime = lastSubmitTime;
    }
}